use_frameworks!

target 'SimplePod_Example' do
  pod 'SimplePod', :path => '../'

  target 'SimplePod_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
